version: 2
jobs:
  build:
    docker:
      - image: reactcommunity/node-ci:8.4.0-0 # custom image -- includes ocaml, libelf1, Yarn
    parallelism: 2
    working_directory: ~/react-navigation
    steps:
      - checkout
      - restore_cache:
          # cache by branch + package.json, by branch, and then master
          keys: 
            - v3-react-navigation-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-react-navigation-{{ .Branch }}
            - v3-react-navigation-master
      - run: yarn # install root deps
      - run: ./scripts/test.sh # run tests
      - save_cache:
          key: v3-react-navigation-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - ~/react-navigation/examples/NavigationPlayground/node_modules
            - ~/react-navigation/examples/ReduxExample/node_modules
