version: 2
jobs:
  build:
    docker:
      - image: reactcommunity/node-ci:7.10.0 # custom image -- includes ocaml, libelf1, Yarn
    parallelism: 3
    working_directory: ~/react-navigation
    steps:
      - checkout
      - restore_cache:
          key: v1-react-navigation-{{ .Branch }} # generate cache per branch
      - run: yarn # install root deps
      - run: ./scripts/test.sh # run tests
      - save_cache:
          key: v1-react-navigation-{{ .Branch }} # generate cache per branch
          paths:
            - ~/.cache/yarn
            - ~/react-navigation/website/node_modules
            - ~/react-navigation/examples/NavigationPlayground/node_modules
            - ~/react-navigation/examples/ReduxExample/node_modules
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploy website
              cd website && yarn && cd ../
              yarn run build-docs
              ./scripts/deploy-website.sh

              # deploy expo playground demo
              yarn global add exp && exp login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
              cd examples/ExpoNavigationPlayground && npm install && exp publish
            fi
